name: Docker Publish


on:
    push:
        branches:
            - main


env:
    REGISTRY: docker.io
    IMAGE_NAME: asifku/private
    TAG: django-drf-v1.0


jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

